name       : perl-file-which
version    : '1.27'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/P/PL/PLICEASE/File-Which-1.27.tar.gz : 3201f1a60e3f16484082e6045c896842261fc345de9fb2e620fd2a2c7af3a93a
homepage   : https://metacpan.org/pod/File::Which
license    :
    - Artistic-1.0-Perl
    - GPL-1.0-or-later
component  : programming.perl
summary    : File::Which - Perl implementation of the which utility as an API
description: |
    File::Which finds the full or relative paths to executable programs on the system. This is normally the function of which utility. which is typically implemented as either a program or a built in shell command. On some platforms, such as Microsoft Windows it is not provided as part of the core operating system. This module provides a consistent API to this functionality regardless of the underlying platform
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
