name       : perl-file-which
version    : '1.22'
release    : 3
source     :
    - https://www.cpan.org/authors/id/P/PL/PLICEASE/File-Which-1.22.tar.gz : e8a8ffcf96868c6879e82645db4ff9ef00c2d8a286fed21971e7280f52cf0dd4
license    :
    - Artistic-1.0
    - GPL-1.0
component  : programming.perl
summary    : Perl File::Which module
description: |
    Perl implementation of the which utility as an API.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
