name       : perl-file-which
version    : '1.23'
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/P/PL/PLICEASE/File-Which-1.23.tar.gz : b79dc2244b2d97b6f27167fc3b7799ef61a179040f3abd76ce1e0a3b0bc4e078
license    :
    - Artistic-1.0-Perl
    - GPL-1.0-or-later
component  : programming.perl
summary    : Perl File::Which module
description: |
    Perl implementation of the which utility as an API.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
