name       : perl-file-which
version    : 1.21
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/P/PL/PLICEASE/File-Which-1.21.tar.gz : 9def5f10316bfd944e56b7f8a2501be1d44c288325309462aa9345e340854bcc
license    :
    - Artistic-1.0
    - GPL-1.0
component  : programming.perl
summary    : Perl File::Which module
description: |
    Perl implementation of the which utility as an API.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
